// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
)

// Get /subscription-data/:ueId/context-data/roaming-information
// Retrieves the Roaming Information of the EPC domain
func HTTPQueryRoamingInformation(c *gin.Context) {
	detail := "Handle Get /subscription-data/:ueId/context-data/roaming-information is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
