// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
)

// Put /exposure-data/:ueId/access-and-mobility-data
// Creates and updates the access and mobility exposure data for a UE
func HTTPCreateOrReplaceAccessAndMobilityData(c *gin.Context) {
	detail := "Handle Put /exposure-data/:ueId/access-and-mobility-data is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Delete /exposure-data/:ueId/access-and-mobility-data
// Deletes the access and mobility exposure data for a UE
func HTTPDeleteAccessAndMobilityData(c *gin.Context) {
	detail := "Handle Delete /exposure-data/:ueId/access-and-mobility-data is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Get /exposure-data/:ueId/access-and-mobility-data
// Retrieves the access and mobility exposure data for a UE
func HTTPQueryAccessAndMobilityData(c *gin.Context) {
	detail := "Handle Get /exposure-data/:ueId/access-and-mobility-data is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Patch /exposure-data/:ueId/access-and-mobility-data
// Updates the access and mobility exposure data for a UE
func HTTPUpdateAccessAndMobilityData(c *gin.Context) {
	detail := "Handle Patch /exposure-data/:ueId/access-and-mobility-data is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
