// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
)

// Put /policy-data/bdt-data/:bdtReferenceId
// Creates an BDT data resource associated with an BDT reference Id
func HTTPCreateIndividualBdtData(c *gin.Context) {
	detail := "Handle Put /policy-data/bdt-data/:bdtReferenceId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Delete /policy-data/bdt-data/:bdtReferenceId
// Deletes an BDT data resource associated with an BDT reference Id
func HTTPDeleteIndividualBdtData(c *gin.Context) {
	detail := "Handle Delete /policy-data/bdt-data/:bdtReferenceId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Get /policy-data/bdt-data/:bdtReferenceId
// Retrieves the BDT data information associated with a BDT reference Id
func HTTPReadIndividualBdtData(c *gin.Context) {
	detail := "Handle Get /policy-data/bdt-data/:bdtReferenceId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Patch /policy-data/bdt-data/:bdtReferenceId
// Modifies an BDT data resource associated with an BDT reference Id
func HTTPUpdateIndividualBdtData(c *gin.Context) {
	detail := "Handle Patch /policy-data/bdt-data/:bdtReferenceId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
