// Copyright (c) 2026 Intel Corporation
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
	"github.com/omec-project/openapi/v2/utils"
	"github.com/omec-project/udr/logger"
	"github.com/omec-project/udr/producer"
	"github.com/omec-project/util/httpwrapper"
)

// Patch /subscription-data/:ueId/context-data/sdm-subscriptions/:subsId
// Modify an individual sdm subscription
func HTTPModifysdmSubscription(c *gin.Context) {
	detail := "Handle Patch /subscription-data/:ueId/context-data/sdm-subscriptions/:subsId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Get /subscription-data/:ueId/context-data/sdm-subscriptions/:subsId
// Retrieves a individual sdmSubscription identified by subsId
func HTTPQuerysdmSubscription(c *gin.Context) {
	detail := "Handle Get /subscription-data/:ueId/context-data/sdm-subscriptions/:subsId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Delete /subscription-data/:ueId/context-data/sdm-subscriptions/:subsId
// Deletes a sdmsubscriptions
func HTTPRemovesdmSubscriptions(c *gin.Context) {
	logger.DataRepoLog.Infoln("Handle Delete /subscription-data/:ueId/context-data/sdm-subscriptions/:subsId")
	req := httpwrapper.NewRequest(c.Request, nil)
	req.Params["ueId"] = c.Params.ByName("ueId")
	req.Params["subsId"] = c.Params.ByName("subsId")

	rsp := producer.HandleRemovesdmSubscriptions(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}

// Put /subscription-data/:ueId/context-data/sdm-subscriptions/:subsId
// Update an individual sdm subscriptions of a UE
func HTTPUpdatesdmsubscriptions(c *gin.Context) {
	logger.DataRepoLog.Infoln("Handle Put /subscription-data/:ueId/context-data/sdm-subscriptions/:subsId")
	var sdmSubscription models.SdmSubscription

	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		logger.DataRepoLog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Decode(&sdmSubscription, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, sdmSubscription)
	req.Params["ueId"] = c.Params.ByName("ueId")
	req.Params["subsId"] = c.Params.ByName("subsId")

	rsp := producer.HandleUpdatesdmsubscriptions(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}
