// Copyright (c) 2026 Intel Corporation
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
	"github.com/omec-project/openapi/v2/utils"
	"github.com/omec-project/udr/logger"
	"github.com/omec-project/udr/producer"
	"github.com/omec-project/util/httpwrapper"
)

// Put /subscription-data/:ueId/context-data/smf-registrations/:pduSessionId
// To create an individual SMF context data of a UE in the UDR
func HTTPCreateOrUpdateSmfRegistration(c *gin.Context) {
	logger.DataRepoLog.Infoln("Handle Put /subscription-data/:ueId/context-data/smf-registrations/:pduSessionId")
	var smfRegistration models.SmfRegistration

	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		logger.DataRepoLog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Decode(&smfRegistration, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, smfRegistration)
	req.Params["ueId"] = c.Params.ByName("ueId")

	rsp := producer.HandleCreateSmfContextNon3gpp(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}

// Delete /subscription-data/:ueId/context-data/smf-registrations/:pduSessionId
// To remove an individual SMF context data of a UE the UDR
func HTTPDeleteSmfRegistration(c *gin.Context) {
	req := httpwrapper.NewRequest(c.Request, nil)
	req.Params["ueId"] = c.Params.ByName("ueId")
	req.Params["pduSessionId"] = c.Params.ByName("pduSessionId")

	rsp := producer.HandleDeleteSmfContext(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}

// Get /subscription-data/:ueId/context-data/smf-registrations/:pduSessionId
// Retrieves the individual SMF registration of a UE
func HTTPQuerySmfRegistration(c *gin.Context) {
	logger.DataRepoLog.Infoln("Handle Get /subscription-data/:ueId/context-data/smf-registrations/:pduSessionId")
	req := httpwrapper.NewRequest(c.Request, nil)
	req.Params["ueId"] = c.Params.ByName("ueId")
	req.Params["pduSessionId"] = c.Params.ByName("pduSessionId")

	rsp := producer.HandleQuerySmfRegistration(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}

// Patch /subscription-data/:ueId/context-data/smf-registrations/:pduSessionId
// To modify the SMF context data of a UE in the UDR
func HTTPUpdateSmfContext(c *gin.Context) {
	detail := "Handle Patch /subscription-data/:ueId/context-data/smf-registrations/:pduSessionId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
