// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
)

// Put /subscription-data/:ueId/context-data/ip-sm-gw
// Create the IP-SM-GW context data of a UE
func HTTPCreateIpSmGwContext(c *gin.Context) {
	detail := "Handle Put /subscription-data/:ueId/context-data/ip-sm-gw is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Delete /subscription-data/:ueId/context-data/ip-sm-gw
// To remove the IP-SM-GW context data of a UE
func HTTPDeleteIpSmGwContext(c *gin.Context) {
	detail := "Handle Delete /subscription-data/:ueId/context-data/ip-sm-gw is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Patch /subscription-data/:ueId/context-data/ip-sm-gw
// Modify the IP-SM-GW context data of a UE
func HTTPModifyIpSmGwContext(c *gin.Context) {
	detail := "Handle Patch /subscription-data/:ueId/context-data/ip-sm-gw is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Get /subscription-data/:ueId/context-data/ip-sm-gw
// Retrieves the IP-SM-GW context data of a UE
func HTTPQueryIpSmGwContext(c *gin.Context) {
	detail := "Handle Get /subscription-data/:ueId/context-data/ip-sm-gw is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
