// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
)

// Put /subscription-data/group-data/5g-vn-groups/:externalGroupId
// Create an individual 5G VN Group
func HTTPCreate5GVnGroup(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Put /subscription-data/group-data/5g-vn-groups/:externalGroupId is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}
