// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
)

// Put /application-data/serviceParamData/:serviceParamId
// Create or update an individual Service Parameter Data resource
func HTTPCreateOrReplaceServiceParameterData(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Put /application-data/serviceParamData/:serviceParamId is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Delete /application-data/serviceParamData/:serviceParamId
// Delete an individual Service Parameter Data resource
func HTTPDeleteIndividualServiceParameterData(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Delete /application-data/serviceParamData/:serviceParamId is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Patch /application-data/serviceParamData/:serviceParamId
// Modify part of the properties of an individual Service Parameter Data resource
func HTTPUpdateIndividualServiceParameterData(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Patch /application-data/serviceParamData/:serviceParamId is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}
