// Copyright (c) 2026 Intel Corporation
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
	"github.com/omec-project/openapi/v2/utils"
	"github.com/omec-project/udr/logger"
	"github.com/omec-project/udr/producer"
	"github.com/omec-project/util/httpwrapper"
)

// Put /subscription-data/:ueId/operator-specific-data
// To create an operator-specific data resource of a UE
func HTTPCreateOperSpecData(c *gin.Context) {
	detail := "Handle Put /subscription-data/:ueId/operator-specific-data is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Delete /subscription-data/:ueId/operator-specific-data
// To remove an operator-specific data resource of a UE
func HTTPDeleteOperSpecData(c *gin.Context) {
	detail := "Handle Delete /subscription-data/:ueId/operator-specific-data is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Patch /subscription-data/:ueId/operator-specific-data
// To modify operator specific data of a UE
func HTTPModifyOperSpecData(c *gin.Context) {
	logger.DataRepoLog.Infoln("Handle Patch /subscription-data/:ueId/operator-specific-data")
	var patchItemArray []models.PatchItem

	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		logger.DataRepoLog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Decode(&patchItemArray, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, patchItemArray)
	req.Params["ueId"] = c.Params.ByName("ueId")

	rsp := producer.HandlePatchOperSpecData(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}

// Get /subscription-data/:ueId/operator-specific-data
// Retrieves the operator specific data of a UE
func HTTPQueryOperSpecData(c *gin.Context) {
	logger.DataRepoLog.Infoln("Handle Get /subscription-data/:ueId/operator-specific-data")
	req := httpwrapper.NewRequest(c.Request, nil)
	req.Params["ueId"] = c.Params.ByName("ueId")

	rsp := producer.HandleQueryOperSpecData(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}
