// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
)

// Put /policy-data/ues/:ueId/ue-policy-set
// Create or modify the UE policy set data for a subscriber
func HTTPCreateOrReplaceUEPolicySet(c *gin.Context) {
	detail := "Handle Put /policy-data/ues/:ueId/ue-policy-set is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Get /policy-data/ues/:ueId/ue-policy-set
// Retrieves the UE policy set data for a subscriber
func HTTPReadUEPolicySet(c *gin.Context) {
	detail := "Handle Get /policy-data/ues/:ueId/ue-policy-set is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Patch /policy-data/ues/:ueId/ue-policy-set
// Modify the UE policy set data for a subscriber
func HTTPUpdateUEPolicySet(c *gin.Context) {
	detail := "Handle Patch /policy-data/ues/:ueId/ue-policy-set is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
