// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
)

// Put /subscription-data/:ueId/ue-update-confirmation-data/upu-data
// To store the UPU acknowledgement information of a UE
func HTTPCreateAuthenticationUPU(c *gin.Context) {
	detail := "Handle Put /subscription-data/:ueId/ue-update-confirmation-data/upu-data is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Get /subscription-data/:ueId/ue-update-confirmation-data/upu-data
// Retrieves the UPU acknowledgement information of a UE
func HTTPQueryAuthUPU(c *gin.Context) {
	detail := "Handle Get /subscription-data/:ueId/ue-update-confirmation-data/upu-data is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
