// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
)

// Put /application-data/iptvConfigData/:configurationId
// Create or update an individual IPTV configuration resource
func HTTPCreateOrReplaceIndividualIPTVConfigurationData(c *gin.Context) {
	detail := "Handle Put /application-data/iptvConfigData/:configurationId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Delete /application-data/iptvConfigData/:configurationId
// Delete an individual IPTV configuration resource
func HTTPDeleteIndividualIPTVConfigurationData(c *gin.Context) {
	detail := "Handle Delete /application-data/iptvConfigData/:configurationId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Patch /application-data/iptvConfigData/:configurationId
// Partial update an individual IPTV configuration resource
func HTTPPartialReplaceIndividualIPTVConfigurationData(c *gin.Context) {
	detail := "Handle Patch /application-data/iptvConfigData/:configurationId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
