// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
)

// Delete /policy-data/ues/:ueId/operator-specific-data
// When the feature OSDResource_Create_Delete is supported, delete OperatorSpecificData resource
func HTTPDeleteOperatorSpecificData(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Delete /policy-data/ues/:ueId/operator-specific-data is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Get /policy-data/ues/:ueId/operator-specific-data
// Retrieve the operator specific policy data of an UE
func HTTPReadOperatorSpecificData(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Get /policy-data/ues/:ueId/operator-specific-data is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Put /policy-data/ues/:ueId/operator-specific-data
// Create or modify the operator specific policy data of a UE
func HTTPReplaceOperatorSpecificData(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Put /policy-data/ues/:ueId/operator-specific-data is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Patch /policy-data/ues/:ueId/operator-specific-data
// Modify the operator specific policy data of a UE
func HTTPUpdateOperatorSpecificData(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Patch /policy-data/ues/:ueId/operator-specific-data is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}
