// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
)

// Put /subscription-data/:ueId/context-data/nidd-authorizations
// Create NIDD Authorization Info
func HTTPCreateNIDDAuthorizationInfo(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Put /subscription-data/:ueId/context-data/nidd-authorizations is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Get /subscription-data/:ueId/context-data/nidd-authorizations
// Retrieve NIDD Authorization Info
func HTTPGetNiddAuthorizationInfo(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Get /subscription-data/:ueId/context-data/nidd-authorizations is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Patch /subscription-data/:ueId/context-data/nidd-authorizations
// Modify NIDD Authorization Info
func HTTPModifyNiddAuthorizationInfo(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Patch /subscription-data/:ueId/context-data/nidd-authorizations is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Delete /subscription-data/:ueId/context-data/nidd-authorizations
// Delete NIDD Authorization Info
func HTTPRemoveNiddAuthorizationInfo(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Delete /subscription-data/:ueId/context-data/nidd-authorizations is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}
