// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
)

// Put /subscription-data/:ueId/context-data/service-specific-authorizations/:serviceType
// Create Service Specific Authorization Info
func HTTPCreateServiceSpecificAuthorizationInfo(c *gin.Context) {
	detail := "Handle Put /subscription-data/:ueId/context-data/service-specific-authorizations/:serviceType is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Get /subscription-data/:ueId/context-data/service-specific-authorizations/:serviceType
// Retrieve Service Specific Authorization Info
func HTTPGetServiceSpecificAuthorizationInfo(c *gin.Context) {
	detail := "Handle Get /subscription-data/:ueId/context-data/service-specific-authorizations/:serviceType is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Patch /subscription-data/:ueId/context-data/service-specific-authorizations/:serviceType
// Modify Service Specific Authorization Info
func HTTPModifyServiceSpecificAuthorizationInfo(c *gin.Context) {
	detail := "Handle Patch /subscription-data/:ueId/context-data/service-specific-authorizations/:serviceType is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Delete /subscription-data/:ueId/context-data/service-specific-authorizations/:serviceType
// Delete Service Specific Authorization Info
func HTTPRemoveServiceSpecificAuthorizationInfo(c *gin.Context) {
	detail := "Handle Delete /subscription-data/:ueId/context-data/service-specific-authorizations/:serviceType is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
