// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
)

// Put /exposure-data/:ueId/session-management-data/:pduSessionId
// Creates and updates the session management data for a UE and for an individual PDU session
func HTTPCreateOrReplaceSessionManagementData(c *gin.Context) {
	detail := "Handle Put /exposure-data/:ueId/session-management-data/:pduSessionId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Delete /exposure-data/:ueId/session-management-data/:pduSessionId
// Deletes the session management data for a UE and for an individual PDU session
func HTTPDeleteSessionManagementData(c *gin.Context) {
	detail := "Handle Delete /exposure-data/:ueId/session-management-data/:pduSessionId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Get /exposure-data/:ueId/session-management-data/:pduSessionId
// Retrieves the session management data for a UE and for an individual PDU session
func HTTPQuerySessionManagementData(c *gin.Context) {
	detail := "Handle Get /exposure-data/:ueId/session-management-data/:pduSessionId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
