// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
)

// Post /application-data/influenceData/subs-to-notify
// Create a new Individual Influence Data Subscription resource
func HTTPCreateIndividualInfluenceDataSubscription(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Post /application-data/influenceData/subs-to-notify is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Get /application-data/influenceData/subs-to-notify
// Read Influence Data Subscriptions
func HTTPReadInfluenceDataSubscriptions(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Get /application-data/influenceData/subs-to-notify is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}
