// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
)

// Put /application-data/bdtPolicyData/:bdtPolicyId
// Create an individual applied BDT Policy Data resource
func HTTPCreateIndividualAppliedBdtPolicyData(c *gin.Context) {
	detail := "Handle Put /application-data/bdtPolicyData/:bdtPolicyId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Delete /application-data/bdtPolicyData/:bdtPolicyId
// Delete an individual Applied BDT Policy Data resource
func HTTPDeleteIndividualAppliedBdtPolicyData(c *gin.Context) {
	detail := "Handle Delete /application-data/bdtPolicyData/:bdtPolicyId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Patch /application-data/bdtPolicyData/:bdtPolicyId
// Modify part of the properties of an individual Applied BDT Policy Data resource
func HTTPUpdateIndividualAppliedBdtPolicyData(c *gin.Context) {
	detail := "Handle Patch /application-data/bdtPolicyData/:bdtPolicyId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
