// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
)

// Put /application-data/pfds/:appId
// Create or update the corresponding PFDs for the specified application identifier
func HTTPCreateOrReplaceIndividualPFDData(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Put /application-data/pfds/:appId is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Delete /application-data/pfds/:appId
// Delete the corresponding PFDs of the specified application identifier
func HTTPDeleteIndividualPFDData(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Delete /application-data/pfds/:appId is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Get /application-data/pfds/:appId
// Retrieve the corresponding PFDs of the specified application identifier
func HTTPReadIndividualPFDData(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Get /application-data/pfds/:appId is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}
