// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
)

// Delete /application-data/influenceData/subs-to-notify/:subscriptionId
// Delete an individual Influence Data Subscription resource
func HTTPDeleteIndividualInfluenceDataSubscription(c *gin.Context) {
	detail := "Handle Delete /application-data/influenceData/subs-to-notify/:subscriptionId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Get /application-data/influenceData/subs-to-notify/:subscriptionId
// Get an existing individual Influence Data Subscription resource
func HTTPReadIndividualInfluenceDataSubscription(c *gin.Context) {
	detail := "Handle Get /application-data/influenceData/subs-to-notify/:subscriptionId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Put /application-data/influenceData/subs-to-notify/:subscriptionId
// Modify an existing individual Influence Data Subscription resource
func HTTPReplaceIndividualInfluenceDataSubscription(c *gin.Context) {
	detail := "Handle Put /application-data/influenceData/subs-to-notify/:subscriptionId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
