// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
)

// Delete /exposure-data/subs-to-notify/:subId
// Deletes the individual Exposure Data subscription
func HTTPDeleteIndividualExposureDataSubscription(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Delete /exposure-data/subs-to-notify/:subId is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Put /exposure-data/subs-to-notify/:subId
// updates a subscription to receive notifications of exposure data changes
func HTTPReplaceIndividualExposureDataSubscription(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Put /exposure-data/subs-to-notify/:subId is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}
