// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
)

// Put /policy-data/ues/:ueId/sm-data/:usageMonId
// Create a usage monitoring resource
func HTTPCreateUsageMonitoringResource(c *gin.Context) {
	detail := "Handle Put /policy-data/ues/:ueId/sm-data/:usageMonId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Delete /policy-data/ues/:ueId/sm-data/:usageMonId
// Delete a usage monitoring resource
func HTTPDeleteUsageMonitoringInformation(c *gin.Context) {
	detail := "Handle Delete /policy-data/ues/:ueId/sm-data/:usageMonId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Get /policy-data/ues/:ueId/sm-data/:usageMonId
// Retrieve a usage monitoring resource
func HTTPReadUsageMonitoringInformation(c *gin.Context) {
	detail := "Handle Get /policy-data/ues/:ueId/sm-data/:usageMonId is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
