// Copyright (c) 2026 Intel Corporation
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/utils"
	"github.com/omec-project/udr/logger"
	"github.com/omec-project/udr/producer"
	"github.com/omec-project/util/httpwrapper"
)

// Delete /subscription-data/group-data/:ueGroupId/ee-subscriptions/:subsId/amf-subscriptions
// Deletes AMF Subscription Info for an eeSubscription for a group of UEs or any UE
func HTTPRemoveAmfGroupSubscriptions(c *gin.Context) {
	detail := "Handle Delete /subscription-data/group-data/:ueGroupId/ee-subscriptions/:subsId/amf-subscriptions is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Delete /subscription-data/:ueId/context-data/ee-subscriptions/:subsId/amf-subscriptions
// Deletes AMF Subscription Info for an eeSubscription
func HTTPRemoveAmfSubscriptionsInfo(c *gin.Context) {
	logger.DataRepoLog.Infoln("Handle Delete /subscription-data/:ueId/context-data/ee-subscriptions/:subsId/amf-subscriptions")
	req := httpwrapper.NewRequest(c.Request, nil)
	req.Params["ueId"] = c.Params.ByName("ueId")
	req.Params["subsId"] = c.Params.ByName("subsId")

	rsp := producer.HandleRemoveAmfSubscriptionsInfo(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}
