// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
)

// Put /subscription-data/:ueId/context-data/ee-subscriptions/:subsId/smf-subscriptions
// Create SMF Subscription Info
func HTTPCreateSMFSubscriptions(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Put /subscription-data/:ueId/context-data/ee-subscriptions/:subsId/smf-subscriptions is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Get /subscription-data/group-data/:ueGroupId/ee-subscriptions/:subsId/smf-subscriptions
// Retrieve SMF Subscription Info for a group of UEs or any UE
func HTTPGetSmfGroupSubscriptions(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Get /subscription-data/group-data/:ueGroupId/ee-subscriptions/:subsId/smf-subscriptions is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Get /subscription-data/:ueId/context-data/ee-subscriptions/:subsId/smf-subscriptions
// Retrieve SMF Subscription Info
func HTTPGetSmfSubscriptionInfo(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Get /subscription-data/:ueId/context-data/ee-subscriptions/:subsId/smf-subscriptions is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Patch /subscription-data/group-data/:ueGroupId/ee-subscriptions/:subsId/smf-subscriptions
// Modify SMF Subscription Info for a group of UEs or any UE
func HTTPModifySmfGroupSubscriptions(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Patch /subscription-data/group-data/:ueGroupId/ee-subscriptions/:subsId/smf-subscriptions is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Patch /subscription-data/:ueId/context-data/ee-subscriptions/:subsId/smf-subscriptions
// Modify SMF Subscription Info
func HTTPModifySmfSubscriptionInfo(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Patch /subscription-data/:ueId/context-data/ee-subscriptions/:subsId/smf-subscriptions is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Delete /subscription-data/group-data/:ueGroupId/ee-subscriptions/:subsId/smf-subscriptions
// Delete SMF Subscription Info for a group of UEs or any UE
func HTTPRemoveSmfGroupSubscriptions(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Delete /subscription-data/group-data/:ueGroupId/ee-subscriptions/:subsId/smf-subscriptions is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}

// Delete /subscription-data/:ueId/context-data/ee-subscriptions/:subsId/smf-subscriptions
// Delete SMF Subscription Info
func HTTPRemoveSmfSubscriptionsInfo(c *gin.Context) {
	logger.DataRepoLog.Warnln("Handle Delete /subscription-data/:ueId/context-data/ee-subscriptions/:subsId/smf-subscriptions is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}
