// Copyright (c) 2026 Intel Corporation
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
	"github.com/omec-project/openapi/v2/utils"
	"github.com/omec-project/udr/logger"
	"github.com/omec-project/udr/producer"
	"github.com/omec-project/util/httpwrapper"
)

// Post /subscription-data/group-data/:ueGroupId/ee-subscriptions
// Create individual EE subscription for a group of UEs or any UE
func HTTPCreateEeGroupSubscriptions(c *gin.Context) {
	logger.DataRepoLog.Infoln("Handle Post /subscription-data/group-data/:ueGroupId/ee-subscriptions")
	var eeSubscription models.EeSubscription
	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		logger.DataRepoLog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Decode(&eeSubscription, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.DataRepoLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, eeSubscription)
	req.Params["ueGroupId"] = c.Params.ByName("ueGroupId")

	rsp := producer.HandleCreateEeGroupSubscriptions(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}

// Get /subscription-data/group-data/:ueGroupId/ee-subscriptions
// Retrieves the ee subscriptions of a group of UEs or any UE
func HTTPQueryEeGroupSubscriptions(c *gin.Context) {
	logger.DataRepoLog.Infoln("Handle Get /subscription-data/group-data/:ueGroupId/ee-subscriptions")
	req := httpwrapper.NewRequest(c.Request, nil)
	req.Params["ueGroupId"] = c.Params.ByName("ueGroupId")

	rsp := producer.HandleQueryEeGroupSubscriptions(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.DataRepoLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}
