// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package datarepository

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/udr/logger"
)

// Post /policy-data/subs-to-notify
// Create a subscription to receive notification of policy data changes
func HTTPCreateIndividualPolicyDataSubscription(c *gin.Context) {
	detail := "Handle Post /policy-data/subs-to-notify is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Get /policy-data/subs-to-notify
// Retrieves the list of Individual Policy Data Subscription resources
func HTTPReadPolicyDataSubscriptions(c *gin.Context) {
	detail := "Handle Get /policy-data/subs-to-notify is not implemented"
	logger.DataRepoLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
