# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 Canonical Ltd.

info:
  version: 1.0.0
  description: UDR initial local configuration

configuration:
  webuiUri: myspecialwebui:9872 # a valid URI of Webui
  sbi: # Service Based Interface
    scheme: https
    registerIPv4: 127.0.0.4
    bindingIPv4: 0.0.0.0
    port: 8000
  mongodb:
    name: free5gc
    url: http://dummy
    authKeysDbName: authentication
    authUrl: http://dummy
